[package]
name = "scirs2-transform"
version = "0.1.0-alpha.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Data transformation module for SciRS2"
keywords = [
  "transform",
  "feature-engineering",
  "scientific",
  "ai",
  "machine-learning",
]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { workspace = true, features = ["validation"] }
scirs2-linalg.workspace = true
scirs2-stats.workspace = true
ndarray = { workspace = true, features = ["serde", "rayon"] }
ndarray-rand = { workspace = true }
ndarray-stats.workspace = true
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true
approx.workspace = true
rayon.workspace = true
rand.workspace = true

# Future dependency for PandRS with appropriate abstractions
# pandrs_wrapper = { path = "../wrappers/pandrs_wrapper", optional = true }

[features]
default = []
# Enable external ML library wrappers
# pandrs = ["dep:pandrs_wrapper"]

[dev-dependencies]
scirs2-datasets.workspace = true
plotters.workspace = true
