[package]
name = "scirs2-io"
version = "0.1.0-alpha.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Input/Output utilities module for SciRS2"
keywords = ["io", "serialization", "data", "scientific", "scipy"]
categories = ["science", "encoding"]

[dependencies]
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
scirs2-core = { path = "../scirs2-core", version = "0.1.0-alpha.2" }
byteorder = "1.4"
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
rmp-serde = "1.1"
flate2 = "1.0"
lz4 = "1.24"
zstd = "0.12"
bzip2 = "0.4"
rand = "0.9.0"
sha2 = "0.10"
crc32fast = "1.3"
blake3 = "1.5"
hex = "0.4"
digest = "0.10"
data-encoding = "2.4"
chrono = "0.4"
tempfile = "3.9"
num-complex = "0.4.6"
regex = "1.10"
glob = "0.3"
netcdf3 = "0.5.2"
