[package]
name = "scirs2-stats"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["SciRS2 Team"]
description = "Statistical functions module for SciRS2"
license = "Apache-2.0"
repository = "https://github.com/cool-japan/scirs"
keywords = ["statistics", "probability", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
num-traits = "0.2.19"
num-complex = "0.4.6"
thiserror = "2.0.12"
ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }
scirs2-core = { version = "0.1.0-alpha.1", path = "../scirs2-core", features = ["validation", "parallel", "simd", "linalg", "openblas"] }
scirs2-linalg = { version = "0.1.0-alpha.1", path = "../scirs2-linalg" }

# Statistics specific dependencies
rand = "0.9.0"
rand_distr = "0.5.1"
rand_pcg = "0.9.0"
statrs = "0.18.0"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"
