[package]
name = "scirs2-cluster"
version = "0.1.0-alpha.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Clustering algorithms module for SciRS2"
keywords = ["clustering", "scientific", "scipy", "numerical", "kmeans"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { path = "../scirs2-core", version = "0.1.0-alpha.2" }
scirs2-spatial = { path = "../scirs2-spatial", version = "0.1.0-alpha.2" }
scirs2-linalg = { path = "../scirs2-linalg", version = "0.1.0-alpha.2" }
scirs2-stats = { path = "../scirs2-stats", version = "0.1.0-alpha.2" }
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }
num-traits = "0.2.19"
thiserror = "2.0.12"
rand = "0.9.0"
approx = "0.5.1"
